#!/bin/bash

build() {
    add_file "/usr/lib/arch-luks-suspend/encrypt-on-suspend" "/bin" 755
}

help() {
    cat <<HELPEOF
This hook installs a /run/initramfs/bin/encrypt-on-suspend script that suspends the encrypted
root device before suspending the system.

You will need the udev, encrypt-on-suspend, and shutdown hooks too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
